#!/bin/bash

# MANUAL INSTALLATION REQUIRED
# The DMG is ready at:

DMG_PATH="/Users/keithbarger/Projects/foodie-meal-planner-desktop/dist/Foodie Meal Planner-1.0.0-arm64.dmg"

echo "=========================================="
echo "FOODIE MEAL PLANNER - INSTALLATION GUIDE"
echo "=========================================="
echo ""
echo "The NEW working build is located at:"
echo ""
echo "  $DMG_PATH"
echo ""
echo "Built: January 19, 2026 at 4:15 PM"
echo "Size: 106 MB"
echo ""
echo "=========================================="
echo "INSTALLATION STEPS:"
echo "=========================================="
echo ""
echo "1. QUIT ALL RUNNING INSTANCES"
echo "   - Open Activity Monitor"
echo "   - Search for 'Foodie'"
echo "   - Quit all instances"
echo ""
echo "2. REMOVE OLD APP (if exists)"
echo "   - Open Finder"
echo "   - Go to Applications folder (Cmd+Shift+A)"
echo "   - Find 'Foodie Meal Planner'"
echo "   - Move to Trash"
echo ""
echo "3. INSTALL NEW VERSION"
echo "   - Double-click the DMG file at:"
echo "     $DMG_PATH"
echo "   - Drag 'Foodie Meal Planner' to Applications folder"
echo "   - Eject the DMG"
echo ""
echo "4. LAUNCH"
echo "   - Open Applications folder"
echo "   - Double-click 'Foodie Meal Planner'"
echo ""
echo "   If macOS blocks it:"
echo "   - System Settings → Privacy & Security"
echo "   - Click 'Open Anyway'"
echo ""
echo "=========================================="
echo "WHAT WAS FIXED:"
echo "=========================================="
echo ""
echo "✅ Removed broken afterPack.js script"
echo "✅ Rebuilt with clean configuration"
echo "✅ App tested and verified working"
echo ""
echo "The app now launches correctly!"
echo ""
echo "=========================================="

# Try to open Finder to the DMG location
open -R "$DMG_PATH"
